### PR TITLE
Bump dependencies for Clojure 1.9.

### PR DESCRIPTION
**Pull request by grzm**
Addresses https://github.com/pedestal/pedestal/issues/456

Change-Id: I4d6c45b6fe7108c6b4741f054b1865e569d46c7d

### CODE REVIEW

**Comment by ohpauleez** [comment]
Sorry if I've asked you this before, but have you signed a Cognitect Contributor's Agreement?

**Comment by grzm** [comment]
I've signed twice :) Once during the old-school paper days, and once with the new digital hotness: http://clojure.org/community/contributors I'm Michael Glaesemann (grzm) on that page.

**Comment by ohpauleez** [comment]
The Clojure CA is different from the Cognitect CA.

The Cognitect CA is used for all Cognitect projects (Transit, Pedestal, etc.) -- At the bottom of [the contributor docs](https://github.com/pedestal/pedestal/blob/master/CONTRIBUTING.md).

**Comment by grzm** [comment]
Ah! Gotcha. Signed and should have been sent to you.

**Comment by ohpauleez** [comment]
Thanks!

**Pull request merged**
