### PR TITLE
Fixes a recursive loop error on aws api gateway utlilities

### PR DESCRIPTION
**Pull request by Adrxx**
Also, corrected the aws-code-star sample code

### CODE REVIEW

**Comment by ohpauleez** [comment]
Thanks for these changes!  Looks like we missed these when we refactored the final version.

Have you signed a [contributor's agreement](https://secure.echosign.com/public/hostedForm?formid=8JU33Z7A7JX84U)?

**Comment by Adrxx** [comment]
Signed ;)

**Comment by Adrxx** [comment]
Also, guys... I'm unable to run your aws-codestar-sample, even with this changes :(

**Comment by ddeaguiar** [comment]
@Adrxx, sorry to hear that you are running into issues. Can you expand on the problems you are running into?

**Comment by Adrxx** [comment]
Done! sorry, as for the error, I don't remember exactly what it said sorry :/, it had something to do with `reduce-kv`... I'll try to look for the exact error.  But anyways I have changed the strategy, I don't use lambdas anymore as the coldstarts are SUPER slow.

**Comment by ddeaguiar** [comment]
@Adrxx sorry for the delayed response but I was out on holiday. We received your CA, thanks! I'll try spinning up this example this week.

**Pull request merged**
