### PR TITLE
Allow overriding the Jetty thread pool

### PR DESCRIPTION
**Pull request by tobias**
This allows consumers to provide a customized thread pool to Jetty via
:container-options.

We are currently using this in [a fork](https://clojars.org/io.clubhouse.forks/pedestal.jetty) to inject an [`InstrumentedQueuedThreadPool`](https://metrics.dropwizard.io/3.1.0/manual/jetty/).

Let me know if you would prefer a different approach to overriding this.

### CODE REVIEW

**Comment by ohpauleez** [comment]
Looks totally fine to me.  On line 244, I would include that the option ignores `:max-threads`

**Comment by tobias** [comment]
Thanks @ohpauleez. I just force-pushed a new commit with your suggestion and the error that was caught by CI.

**Comment by ddeaguiar** [comment]
Hi @tobias, thanks for contributing to Pedestal! Have you signed a [Contributor's Agreement](https://github.com/pedestal/pedestal/blob/master/CONTRIBUTING.md#contributors-agreement)?

**Comment by tobias** [comment]
@ddeaguiar I have now, thanks for the reminder!

**Comment by tobias** [comment]
Thanks for merging @ddeaguiar. Any idea of when you will be doing the next release?

**Pull request merged**
