### PR TITLE
Trailing slash NPE

### LINKED ISSUE #340: Exceptions for routes with path params
Pedestal 0.4.0 or 0.4.1-SNAPSHOT at 73b5854d.

Given this route:

    (defroutes routes [[["/a/:a/b/:b" {:get my-page}]]])

* I get a 500 response because of a NullPointerException [here](https://github.com/pedestal/pedestal/blob/73b5854d4ba01a6cd2146ca8a37ae6a2b76e8995/service/src/io/pedestal/http/route/prefix_tree.clj#L321) when requesting `/a/`, `/a/a` or `/a/a/b/`.
* When I request `/a`, `/a/a/b` or `/a/a/b/b/c` I get a 404 as expected.
* When I request `/a/a/` or `/a/a/b/b/` I get a 500 because of a StringIndexOutOfBoundsException [here](https://github.com/pedestal/pedestal/blob/73b5854d4ba01a6cd2146ca8a37ae6a2b76e8995/service/src/io/pedestal/http/route/prefix_tree.clj#L31).
* Requesting `/a/a/b/b` works fine.

### PR DESCRIPTION
**Pull request by jcf**
Given the following routes:

- `/people`
- `/people/:id`

…it was possible to get a 500 error via an NPE when visiting `/people/`, which obviously isn't what we want.

Based on an hour or so of reading lots of posts and opinion on whether URLs and RESTful routes should use trailing slashes I've concluded it's best to leave it up to the author (in this case the user of Pedestal). To support this I've made two changes to the prefix router. The first change checks a wildcard route not only contains a `/` but also that it's not the final character in the URL, and I've made sure we only ever call the `:payload` function for a route when it exists.

I can't say for sure this is the best solution, although I considered some alternatives like cleaning routes before inserting them, and enforcing certain good URL practices (forcing a trailing slash when adding a collection route) but opted for this approach because to my knowledge it will not break any existing Pedestal apps, and is relatively small/simple.

It's late here so please forgive any ambiguity. I'm happy to answer any questions you might have, and welcome feedback.

Fixes #340.

- http://googlewebmastercentral.blogspot.co.uk/2010/04/to-slash-or-not-to-slash.html
- http://programmers.stackexchange.com/questions/186959/trailing-slash-in-restful-api
- http://programmers.stackexchange.com/questions/186959/trailing-slash-in-restful-api
- http://sebastians-pamphlets.com/thou-must-not-steal-the-trailing-slash-from-my-urls/
- http://stackoverflow.com/questions/5948659/trailing-slash-in-urls-which-style-is-preferred
- http://www.bizcoder.com/the-mystery-of-the-trailing-slash-and-the-relative-url
- https://cdivilly.wordpress.com/2014/03/11/why-trailing-slashes-on-uris-are-important/
- https://github.com/nicolaiarocci/eve/issues/118
- https://www.safaribooksonline.com/library/view/rest-api-design/9781449317904/ch02s02.html (this one I particularly dislike as there's no evidence or justification for why this is the right approach)

---

**N.B.** This contains my small fix for enabling the trailing slash tests for the linear search router. I can remove that commit easily enough if necessary.

### CODE REVIEW

**Comment by ohpauleez** [comment]
Just a note - the error isn't with the linear router, it's with the prefix tree router.

**Comment by jcf** [comment]
Thanks @ohpauleez.

**Comment by jcf** [comment]
Hey @ohpauleez. I've got a passing build and a potential solution I'd appreciate your opinion on. I'm calling it a night, but will be around tomorrow if you come back with anything.

**Comment by ohpauleez** [comment]
This issue was addressed in #361 - If you find the problem still pops up, open up a new issue.  Thanks!

**Pull request closed without merging**
