### PR TITLE
response-for should wait for the resp to be realized

### PR DESCRIPTION
**Pull request by briprowe**
This is a potential resolution for #316.

There are some magic numbers in this commit that hard-code how long to wait for the response. I think it would be good to make these parameters that the testing code can provide. I didn't add that to this commit, because that would change the api. Let me know if you think we should do that.

### CODE REVIEW

**Comment by ohpauleez** [comment]
Thanks for digging in and putting together this pull request!  I greatly appreciate it when people are willing to roll up their sleeves.  I'm going to close this particular PR - as stated in #316, I rather see a channel used than a promise with a timeout (for handling async responses).

**Comment by briprowe** [comment]
You're right. Timeouts are a pain!

What does a more ideal solution look like? I presume it plays nicely with code doing SSE? Do you think the changes needed to get there might be (mostly) contained in `io.pedestal.test`? Or, do you think it may require deeper changes?

**Comment by ohpauleez** [comment]
I'm not entirely sure what the ideal solution looks like.

I'd imagine the new `response-for` should work for all request formats (sync, async by channel, async by NIO, SSE, and soon WebSockets, which will be channel-based too).  For now, it'd be good enough just to work with sync and async behavior.  I think the changes are all contained within io.pedestal.test, and I think we can even keep backwards compatibility - allowing people to migrate up when needed.

**Comment by briprowe** [comment]
How would this work with websockets?  Since a websocket is full-duplex, would we need 2 channels?

**Pull request closed without merging**
