### PR TITLE
update samples/hello-world/README.md

### PR DESCRIPTION
**Pull request by NazarDunets**

### CODE REVIEW

**Review by devurandom — APPROVED** [review]
The fix in this PR is correct: https://github.com/pedestal/pedestal/blob/master/samples/hello-world/src/hello_world/service.clj#L21-L22

**Comment by bonkydog** [comment]
Hello, @NazarDunets!  

Nice catch!  

We'd like to integrate your contribution into the project, but in order to do this we need to get a signed Contributor Agreement from you. Please find instructions on how (and why) to do this here:

http://pedestal.io/community/contributing#_contributors_agreement

Thanks!

**Comment by NazarDunets** [comment]
Hey, @bonkydog . I've signed the agreement.

**Review by bonkydog — APPROVED** [review]
Thanks for catching this! :rocket:

**Pull request merged**
