### PR TITLE
improve csrf interceptor

### PR DESCRIPTION
**Pull request by lucywang000**
* support `:cookie-attrs` for setting csrf cookie attribute like path, http-only, etc.
* add support for rotating the csrf token, which shall be done after login succeeds

TODO: 
- [x] fix failed tests
- [x] add tests for the changes

### CODE REVIEW

**Comment by ohpauleez** [comment]
Hi @lucywang000 - thanks for so much interest in contributing!

We encourage community members to open an issue first regarding proposed changes, giving other community members a chance to contribute ideas/experience reports/etc.  It also lets core contributors a chance to comment with additional context.

What problems does `:cookie-attrs` solve?  It seems like another interceptor could set cookies as needed?  Introducing this change would be a breaking change, so we're not likely to accept this particular change.

Did you consider other alternatives for token rotation?  For example, I've often considered exposing other functions like `session-token` or line 135 (like you did) but exposing it as an option `anti-forgery-token` (which is why it is structured the way it is currently).  In the past, when I required token rotation, I introduced that at the application level.  What challenges are you facing that are preventing you from controlling rotation outside the core CSRF interceptor?

**Comment by lucywang000** [comment]
> We encourage community members to open an issue first regarding proposed changes, giving other community members a chance to contribute ideas/experience reports/etc. It also lets core contributors a chance to comment with additional context.

@ohpauleez thanks for the context. Sorry for not following that convention, now I know how to start  with future prs :)

> What problems does :cookie-attrs solve?

It would be useful to be able to set the path and max age of csrf cookies, for example. 

> Introducing this change would be a breaking change, so we're not likely to accept this particular change.

Nope, the default cookie-attrs is empty, so it'll be exactly as before.

> In the past, when I required token rotation, I introduced that at the application level.
>  What challenges are you facing that are preventing you from controlling rotation outside the core CSRF interceptor?

Emm, correct token rotation is essential to security so I'd argue it'll be better provided out of the box in the library level. For example ring session middleware supports recreating the session id by checking the meta of the session key: https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/session.clj#L47

**Comment by ddeaguiar** [comment]
@lucywang000, thanks for contributing to Pedestal.  While the approach in the PR seems reasonable, we’d prefer to approach these kind of changes more rigorously through an issue which clarifies the problem, includes a discussion of options and identifies a solution, especially when it involves API changes or additions.  I'm going to open an issue which references this PR. In the meantime token rotation can be implemented at the application level.

**Comment by ddeaguiar** [comment]
@lucywang000, can you also submitted a [Contributor's Agreement](https://github.com/pedestal/pedestal/blob/master/CONTRIBUTING.md#contributors-agreement)?

**Comment by lucywang000** [comment]
Thanks @ddeaguiar ! I submitted the CLA.

**Comment by bonkydog** [comment]
Hello, Lucy!

Thank you for contributing to Pedestal!

Sorry it's taken us such a log time to get around to addressing your Pull Request. We'd like to integrate your contribution into the project, but, well, our records show that we have a signed Contributor Agreement from you but they don't link your contribution to your GitHub username.

Would you please sign a fresh CA for us? Sorry about the mix-up.

http://pedestal.io/community/contributing#_contributors_agreement

Thanks!
Brian

**Comment by lucywang000** [comment]
@bonkydog done!

**Review by hlship — APPROVED** [review]

**Comment by hlship** [comment]
I think I screwed things up trying to push my merge, or at least, the fix after the merge. Anyway I'd say merge this to master and we can fix the broken test in master.

**Comment by lucywang000** [comment]
Thanks @bonkydog !

**Pull request merged**
