### PR TITLE
Translate jetty websock sample to immutant

### PR DESCRIPTION
**Pull request by jimrthy**
This is really just the jetty websocket sample with a few minor variations.

### CODE REVIEW

**Comment by ohpauleez** [comment]
Thanks for pulling this together.  I'll get this reviewed and landed (and then use it to tackle the enhancement/issue mentioned in the other ticket).

**Comment by tooke7** [comment]
Can this be merged? I just did this translation myself-- and then I found this as I was about to submit my own PR ;)

**Comment by bonkydog** [comment]
Hello, James!

Sorry it's taken us such a log time to get around to addressing your Pull Request. We'd like to integrate your contribution into the project, but in order to do this we need to get a signed Contributor Agreement from you.

Please find instructions on how (and why) to do this here:

http://pedestal.io/community/contributing#_contributors_agreement

Thanks!
Brian

**Comment by hlship** [comment]
Thank you for contributing to Pedestal!
    
    Sorry it's taken us such a log time to get around to addressing your Pull Request. We'd like to integrate your contribution into the project, but in order to do this we need to get a signed Contributor Agreement from you.
    Please find instructions on how (and why) to do this here:
    
    http://pedestal.io/community/contributing#_contributors_agreement
    
    Thanks!

**Pull request closed without merging**
